### ISSUE TITLE
does this work with Sapper / in SSR? I get a 500 error

### ISSUE THREAD

**Issue by skdigital** [matyunya/svelte-image#21] opened 2019-10-09 14:38 UTC
I followed the instructions but I get a stack trace 500 error.

Stacktrace
```
500
<Image> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Error: <Image> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:213:15)
    at C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:267:8
    at Object.$$render (C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:231:22)
    at C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:329:49
    at Object.$$render (C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:231:22)
    at Object.default (C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:770:204)
    at C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:557:39
    at Object.$$render (C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:231:22)
    at C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:768:43
    at $$render (C:\Users\sean\dev\clients\ucp-group\site-ucpgroup-sapper__sapper\dev\server\server.js:231:22)
```

**Comment by matyunya** [comment] 2019-10-10 01:20
Did you add svelte-image to both client and server configs?

You may refer to my project, it's using both: https://github.com/matyunya/teatralium-smelte.

**Comment by skdigital** [comment] 2019-10-10 15:28
Ok will get back to you, seem to still be getting the 500 error flashing up on the screen. Will post screenshots of my setup, maybe you can see where I am going wrong.

**Comment by skdigital** [comment] 2019-10-19 16:12
Nope every project I keep getting a flashed Error page 500 when using Sapper SSR

Here are project files:

Rollup config 
```javascript

import resolve from "rollup-plugin-node-resolve";
import replace from "rollup-plugin-replace";
import commonjs from "rollup-plugin-commonjs";
import svelte from "rollup-plugin-svelte";
import babel from "rollup-plugin-babel";
import { terser } from "rollup-plugin-terser";
import config from "sapper/config/rollup.js";
import pkg from "./package.json";

// USER IMPORTED
import image from "svelte-image";
// import getPreprocessor from "svelte-preprocess";

const mode = process.env.NODE_ENV;
const dev = mode === "development";
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) =>
  (warning.code === "CIRCULAR_DEPENDENCY" &&
    /[/\\]@sapper[/\\]/.test(warning.message)) ||
  onwarn(warning);
const dedupe = importee =>
  importee === "svelte" || importee.startsWith("svelte/");

// USER ADDED
const preprocess = [
  image({
    sizes: [600, 900, 1200],
    optimizeAll: true,
    trace: {
      background: "transparent",
      color: "#D473D4",
      threshold: 200
    }
  })
];

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    plugins: [
      replace({
        "process.browser": true,
        "process.env.NODE_ENV": JSON.stringify(mode)
      }),
      svelte({
        dev,
        hydratable: true,
        emitCss: true,
        preprocess
      }),
      resolve({
        browser: true,
        dedupe
      }),
      commonjs(),

      legacy &&
        babel({
          extensions: [".js", ".mjs", ".html", ".svelte"],
          runtimeHelpers: true,
          exclude: ["node_modules/@babel/**"],
          presets: [
            [
              "@babel/preset-env",
              {
                targets: "> 0.25%, not dead"
              }
            ]
          ],
          plugins: [
            "@babel/plugin-syntax-dynamic-import",
            [
              "@babel/plugin-transform-runtime",
              {
                useESModules: true
              }
            ]
          ]
        }),

      !dev &&
        terser({
          module: true
        })
    ],

    onwarn
  },

  server: {
    input: config.server.input(),
    output: config.server.output(),
    plugins: [
      replace({
        "process.browser": false,
        "process.env.NODE_ENV": JSON.stringify(mode)
      }),
      svelte({
        generate: "ssr",
        dev,
        preprocess
      }),
      resolve({
        dedupe
      }),
      commonjs()
    ],
    external: Object.keys(pkg.dependencies).concat(
      require("module").builtinModules ||
        Object.keys(process.binding("natives"))
    ),

    onwarn
  },

  serviceworker: {
    input: config.serviceworker.input(),
    output: config.serviceworker.output(),
    plugins: [
      resolve(),
      replace({
        "process.browser": true,
        "process.env.NODE_ENV": JSON.stringify(mode)
      }),
      commonjs(),
      !dev && terser()
    ],

    onwarn
  }
};
```

Index.js file
```javascript

<script>
  import Image from "svelte-image";
</script>

<style>
  h1,
  figure,
  p {
    text-align: center;
    margin: 0 auto;
  }

  h1 {
    font-size: 2.8em;
    text-transform: uppercase;
    font-weight: 700;
    margin: 0 0 0.5em 0;
  }

  figure {
    margin: 0 0 1em 0;
  }

  /* img {
    width: 100%;
    max-width: 400px;
    margin: 0 0 1em 0;
  } */

  p {
    margin: 1em auto;
  }

  @media (min-width: 480px) {
    h1 {
      font-size: 4em;
    }
  }
</style>

<svelte:head>
  <title>Sapper project template</title>
</svelte:head>

<h1>Great success!</h1>

<figure>
  <Image alt="Borat" src="great-success.png" />
  <figcaption>HIGH FIVE!</figcaption>
</figure>

<p>
  <strong>
    Try editing this file (src/routes/index.svelte) to test live reloading.
  </strong>
</p>

```

**Comment by skdigital** [comment] 2019-10-21 21:55
Seems like I am getting the 500 error by using the Image component in Sapper, can the Image component be used with Sapper if so what am I doing wrong?

```
Error: &lt;Image&gt; is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

**Comment by skdigital** [comment] 2019-10-22 12:52
@matyunya any help would be greatly appreciated!

**Comment by skdigital** [comment] 2019-10-24 23:10
Hi mate, any movement on this? It would be great to know why I am getting the error if this is a standard error or why its not working for me using Sapper?

**Comment by matyunya** [comment] 2019-10-28 14:05
Hey! Sorry, been away from computer for a while. I don't see any problems with your code. I wonder if it has something to do with npm/node/some package version going wrong. Can you upload your repo somewhere?

**Comment by skdigital** [comment] 2019-10-31 15:37
how can we do this privately?

**Comment by matyunya** [comment] 2019-11-01 00:05
matyunya#6803 discord

**Comment by dotpc** [comment] 2019-11-02 19:00
Hi, I have the same problem. Do I need to provide any information?

**Comment by happycollision** [comment] 2019-11-06 05:52
Interesting. I am having the same problem, but assumed it was a constraint of svelte-waypoint. I'd be interested in the fix for this, too. If I get to a point where it is getting in the way of my app, I'll investigate as well and open a PR if I figure it out.

**Comment by matyunya** [comment] 2019-11-06 05:59
@happycollision can you please upload a repo where you get the problem? I'm unable to reproduce it locally.

**Comment by happycollision** [comment] 2019-11-06 07:26
https://github.com/postplayhouse/postplayhouse.com

It is large and seems to be taking a while to push, but it will eventually be there (I hope!)

There is a branch for the failure. `yarn && yarn dev` to run the app on http://localhost:3000

**Comment by MassivDash** [comment] 2019-11-06 12:12
I have encountered the 500 flashes, however moving the svelte-image to dev dependencies solved the issue for me.

**Comment by happycollision** [comment] 2019-11-06 15:57
Interesting.

~Don

**Comment by happycollision** [comment] 2019-11-07 04:03
Yep. That fixes it. Thanks for the tip, @MassivDash!

### Fix for broken SSR
Be sure to include `svelte-image` as one of your `devDependencies` in your `package.json`. Including it under `dependencies` will cause issues.

I haven't seen any documentation on this, so I do not know if it is a bug in Sapper, or if it is working as intended. It is odd that the component still _works_ as a dev dependency, but won't SSR.

**Comment by matyunya** [comment] 2019-11-07 04:07
I'll upgrade readme then. I suppose this has something to do with the `svelte` section in `package.json`:
```
"svelte": "src/Image.svelte",
"main": "src/index.js", // this gets imported rather than the previous line
```

**Closed by matyunya** 2019-11-07 04:07 UTC

**Comment by happycollision** [comment] 2019-11-07 04:42
I think Svelte compiler uses both? `index.js` for server stuff and `Image.svelte` for the actual component. 

I don't actually use `<Image />` at all in my current project, but `svelte-image` still runs on all my regular image tags. (I added an Image tag to show the breakage.)
